# This is a basic workflow that is manually triggered

name: Run Mvn tests

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
jobs:
  test:
#    runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
    - name: Configure Datadog Test Visibility
      uses: datadog/test-visibility-github-action@v2
      with:
        languages: java
        service: my-service
        api_key: ${{ secrets.DD_API_KEY }}
        site: datadoghq.com
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Setup Maven
      uses: stCarolas/setup-maven@v5
    - uses: actions/checkout@v4
    - name: check java
      run: |
        java --version
    # - run: sbt --version
    - name: Run mvn api
      run: mvn clean test -Dsuite=api
